- hosts: web
  sudo: yes
  vars:
    mysql_root_password: root
    mysql_users:
      - name: symfony
        host: "%"
        password: symfony
        priv: "*.*:ALL"
    php_packages:
      - php7.1-fpm
      - php7.1-cli
      - php7.1-curl
      - php7.1-dev
      - php7.1-intl
      - php7.1-xdebug
      - php7.1-imap
      - php7.1-mbstring
      - php7.1-opcache
      - php7.1-apcu
      - php7.1-bcmath
      - php7.1-xml
      - php7.1-mysql
    timezone: Europe/Brussels

  roles:
    - { role: php}
    - { role: composer}
    - { role: symfony }
    - { role: geerlingguy.mysql }


