---
- name: download symfony
  get_url:
    url: https://symfony.com/installer
    dest: /usr/local/bin/symfony

- name: make symfony executable
  file:
    path: /usr/local/bin/symfony
    mode: a+x
    state: file
